package com.night.backgroundchange;

import androidx.appcompat.app.AppCompatActivity;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.widget.FrameLayout;
import android.widget.TextView;
import android.graphics.Color;

public class MainActivity extends AppCompatActivity {
    static {
        System.loadLibrary("game_logic");
    }

    public native String stringFromJNI();
    public native void initNativeLevel(int[] data);
    public native boolean canArrowMove(int arrowId);
    public native void removeNativeArrow(int arrowId);

    private GameEngine gameEngine;
    private MediaPlayer clickPlayer;
    private MediaPlayer winPlayer;
    private boolean soundEnabled = true;
    private boolean isSurfaceReady = false;
    
    // Step logger
    private TextView statusTracker;
    private StringBuilder statusLog = new StringBuilder();

    private void logStep(String message) {
        runOnUiThread(() -> {
            statusLog.append("✔ ").append(message).append("\n");
            if (statusTracker != null) {
                statusTracker.setText(statusLog.toString());
            }
        });
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        // 1. Force tracking view layout immediately to see text on screen
        FrameLayout mainLayout = new FrameLayout(this);
        mainLayout.setBackgroundColor(Color.BLACK);

        statusTracker = new TextView(this);
        statusTracker.setTextColor(Color.GREEN);
        statusTracker.setTextSize(14);
        statusTracker.setPadding(40, 80, 40, 40);
        statusTracker.setText("Initializing diagnostics...\n");
        
        // This container will hold the game view beneath our text
        FrameLayout gameContainer = new FrameLayout(this);
        gameContainer.setId(View.generateViewId());
        
        mainLayout.addView(gameContainer);
        mainLayout.addView(statusTracker); // Keeps text visible on top!
        setContentView(mainLayout);

        logStep("App opened. Main tracking overlay active.");

        // 2. Test JNI connection
        try {
            String jniCheck = stringFromJNI();
            logStep("JNI Connected successfully: " + jniCheck);
        } catch (Throwable t) {
            logStep("FAILED JNI LINK: " + t.getMessage());
        }

        // 3. Load audio streams
        try {
            clickPlayer = MediaPlayer.create(this, R.raw.click);
            winPlayer = MediaPlayer.create(this, R.raw.completelevel);
            logStep("Audio assets loaded cleanly.");
        } catch (Exception e) {
            logStep("Audio initialization skipped or missing files.");
        }

        // 4. Fire up the game engine view instance
        try {
            logStep("Instantiating GameEngine layout view...");
            gameEngine = new GameEngine(this, this);
            gameContainer.addView(gameEngine);
            logStep("GameEngine view successfully appended to layout hierarchy.");
        } catch (Throwable engineError) {
            logStep("CRASH INSIDE ENGINE CONSTRUCTOR: " + engineError.getMessage());
        }

        // 5. Send parameters to C++
        try {
            int[] secureStarterGrid = new int[200]; 
            for (int i = 0; i < secureStarterGrid.length; i++) {
                secureStarterGrid[i] = 1; 
            }
            initNativeLevel(secureStarterGrid);
            logStep("Initial 200-element tracking matrix sent down to C++ layer.");
        } catch (Throwable nativeError) {
            logStep("Native matrix array sync failed.");
        }

        // 6. Monitor hardware surface creation
        if (gameEngine instanceof SurfaceView) {
            logStep("Detected SurfaceView design architecture. Awaiting hardware callback...");
            SurfaceHolder holder = ((SurfaceView) gameEngine).getHolder();
            holder.addCallback(new SurfaceHolder.Callback() {
                @Override
                public void surfaceCreated(SurfaceHolder holder) {
                    isSurfaceReady = true;
                    logStep("Hardware surface generated by system. Triggering loop activation...");
                    try {
                        gameEngine.resume();
                        logStep("gameEngine.resume() invoked successfully!");
                    } catch (Throwable t) {
                        logStep("Error loop hanging inside engine.resume(): " + t.getMessage());
                    }
                }

                @Override
                public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                    logStep("Surface layout resized to: " + width + "x" + height);
                }

                @Override
                public void surfaceDestroyed(SurfaceHolder holder) {
                    isSurfaceReady = false;
                    logStep("Surface view window torn down.");
                    if (gameEngine != null) {
                        gameEngine.pause();
                    }
                }
            });
        } else {
            logStep("Standard custom view architecture detected. Initializing post-draw sequence.");
            gameContainer.post(() -> {
                isSurfaceReady = true;
                if (gameEngine != null) {
                    gameEngine.resume();
                    logStep("Engine thread resume loop started via layout delay path.");
                }
            });
        }
    }

    public void playSound(boolean isWin) {
        if (!soundEnabled) return;
        if (isWin) {
            if (winPlayer != null) winPlayer.start();
        } else {
            if (clickPlayer != null) clickPlayer.start();
        }
    }

    public void onLevelComplete() {
        playSound(true);
        runOnUiThread(() -> {
            if (gameEngine != null) {
                gameEngine.loadLevel(2);
            }
        });
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (gameEngine != null && isSurfaceReady) {
            gameEngine.resume();
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (gameEngine != null) {
            gameEngine.pause();
        }
    }
}
