# Project-wide Gradle settings.

# Enable AndroidX and Jetifier to fix duplicate class build collisions
android.useAndroidX=true
android.enableJetifier=true

# Optimize build performance
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true

# Force clean, non-cached evaluation sequence
org.gradle.configuration-cache=false
org.gradle.configureondemand=false
org.gradle.isolatedprojects=false

# JVM Allocation
android.experimental.additional-jvm-args=-Xmx2048m
