plugins {
    id 'com.android.application'
}

android {
    namespace 'com.night.backgroundchange'
    compileSdk 34
    
    // 1️⃣ ADD THIS LINE HERE to force Gradle to target the correct NDK version
    ndkVersion "25.1.8937393"

    defaultConfig {
        applicationId "com.night.backgroundchange"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                cppFlags "-std=c++17"
            }
        }
    }

    signingConfigs {
        release {
            storeFile file("../Night_Shadow_Main_Key.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    
    externalNativeBuild {
        cmake {
            path file('src/main/Cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
